# Generated by Django 6.0.1 on 2026-03-11 15:36

import django.utils.timezone
import web.utils.CustomUUID
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', web.utils.CustomUUID.UUIDField(editable=False, max_length=30, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('order_number', models.IntegerField(blank=True, default=0, null=True)),
                ('prompt', models.TextField(blank=True, default='', max_length=10000, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'system prompt',
                'ordering': ['-created_at'],
            },
        ),
    ]
