# Generated by Django 6.0.1 on 2026-02-14 16:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import web.models.Character
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', web.models.Character.UUIDField(editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to=web.models.Character.photo_upload_to, validators=[django.core.validators.validate_image_file_extension, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), web.models.Character.validate_photo_size])),
                ('profile', models.TextField(max_length=100000)),
                ('background_photo', models.ImageField(upload_to=web.models.Character.background_photo_upload_to, validators=[django.core.validators.validate_image_file_extension, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), web.models.Character.validate_background_photo_size])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'digisoul character',
                'ordering': ['-created_at'],
            },
        ),
    ]
