# Generated by Django 6.0.1 on 2026-03-15 15:11

import django.core.validators
import web.models.Friends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_message_audio_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='tts_audio',
            field=models.FileField(blank=True, default=None, null=True, upload_to=web.models.Friends.audio_upload_to, validators=[web.models.Friends.validate_audio_file_extension, django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'm4a'])], verbose_name='TTS语音文件'),
        ),
    ]
