# Generated by Django 6.0.1 on 2026-03-16 14:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import web.models.Character
import web.utils.CustomUUID
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_message_tts_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', web.utils.CustomUUID.UUIDField(editable=False, unique=True)),
                ('voice_name', models.CharField(default='', max_length=100, verbose_name='音色名称')),
                ('voice_types', models.CharField(default='', max_length=100, verbose_name='音色类型')),
                ('voice_speed', models.FloatField(default=1.0, verbose_name='语速')),
                ('voice_pitch', models.FloatField(default=1.0, verbose_name='音调')),
                ('voice_volume', models.FloatField(default=50, verbose_name='音量')),
                ('voice_style', models.CharField(default='', max_length=100, verbose_name='音色风格')),
                ('voice_emotion', models.CharField(default='', max_length=100, verbose_name='音色情感')),
                ('voice_language', models.CharField(choices=[('zh', '中文'), ('en', '英文'), ('ja', '日文'), ('ko', '韩文')], default='zh', max_length=100, verbose_name='音色语言')),
                ('preview_voice', models.FileField(blank=True, default=None, null=True, upload_to=web.models.Character.audio_upload_to, validators=[web.models.Character.validate_audio_file_extension, django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'm4a'])], verbose_name='TTS语音文件')),
                ('preview_text', models.CharField(default='你好，请问有什么事情嘛？', max_length=100, verbose_name='试听文本')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=100, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='friends',
            name='intimacy_score',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='好感度/亲密度'),
        ),
        migrations.CreateModel(
            name='CharacterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', web.utils.CustomUUID.UUIDField(editable=False, unique=True)),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('short_profile', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='角色简介')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_settings', to='web.character', to_field='uuid')),
                ('voice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_voice', to='web.charactervoice', to_field='uuid')),
            ],
            options={
                'verbose_name': 'digisoul character settings',
                'ordering': ['-created_at'],
            },
        ),
    ]
