# Generated by Django 6.0.1 on 2026-03-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_charactervoice_character_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digisouluser',
            name='account_level',
            field=models.CharField(blank=True, choices=[('free', '免费'), ('pro', '专业'), ('ultra', '超级')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='digisouluser',
            name='cas_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
