# Generated by Django 6.0.1 on 2026-03-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_digisouluser_account_level_digisouluser_cas_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='digisouluser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='digisouluser',
            name='cas_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
