# Generated by Django 6.0.1 on 2026-03-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_digisouluser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digisouluser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
